---
nextcloud_image: nextcloud
nextcloud_port: "4445"
nextcloud_data_volume: /opt/nextcloud
nextcloud_env:
  NEXTCLOUD_ADMIN_USER: cookie-admin
  NEXTCLOUD_ADMIN_PASSWORD: "{{ lookup('file', 'files/secrets/user-pass') }}"
