---
- hosts: main

  roles:
    - geerlingguy.pip

  tasks:
    - name: Install Python 3.x
      apt:
        name: python3
        state: present

    - name: Install packages
      pip:
        executable: pip3
        name: "{{ item }}"
      loop:
        - docker
        - requests
