---
- hosts: main

  tasks:
    - name: Install Python 3.x
      apt:
        name: python3
        state: present

    - name: Install Pip
      apt:
        name: pip3
        state: present

    - name: Install Docker
      pip:
        name: docker
