---
# https://www.cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux/
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes cache_valid_time=3600 force_apt_get=yes

    - name: Upgrade all packages
      apt: upgrade=dist force_apt_get=yes

    - name: Check if reboot is required
      stat: path=/var/run/reboot-required get_md5=no
      register: reboot_required_file

    - name: Reboot the server if required
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      # TODO: only do update in case specifically instructed
      when: reboot_required_file.stat.exists
