---
image_name: docker-radicale
container_name: radicale
docker_git: https://github.com/c00k133/docker-radicale.git#master
dockerfile: Dockerfile.extended
published_ports:
  - 127.0.0.1:5232:5232
security_opts:
  - "no-new-privileges:true"
cap_drops:
  - ALL
cap_adds:
  - CHOWN
  - SETUID
  - SETGID
  - KILL
pids_limit: 50
memory: 256M
healthcheck:
  test: ["CMD", "curl", "--fail", "http://localhost:5232", "||", "exit", "1"]
  interval: 30s
  retries: 3
volumes:
  - /var/lib/radicale:/data
  - /etc/radicale/config:/config:ro
  - /var/log/docker/radicale:/var/log
