#!/bin/bash

BACKUP_DIRECTORY="{{ password_database_backup_directory }}"
PASSWORD_DATABASE_DUMP_PREFIX="{{ password_database_dump_prefix }}"
PASSWORD_DATABASE_LOCATION="{{ password_database_location }}"
INTEGRITY_FILE="${BACKUP_DIRECTORY}.integrity"
NEW_BACKUP="${BACKUP_DIRECTORY}${PASSWORD_DATABASE_DUMP_PREFIX}$(date +%y%m%d).kdbx"

INTEGRITY_CHECK=$(sha256sum "${PASSWORD_DATABASE_LOCATION}")
LAST_SHASUM=$(cat "${INTEGRITY_FILE}")

if [ "${INTEGRITY_CHECK}" != "${LAST_SHASUM}" ]; then
    rm "$(ls -t1 "${BACKUP_DIRECTORY}"${PASSWORD_DATABASE_DUMP_PREFIX}* | tail -n +10)" 2>/dev/null
    cp "${PASSWORD_DATABASE_LOCATION}" "${NEW_BACKUP}"

    echo "${INTEGRITY_CHECK}" > "${INTEGRITY_FILE}"
fi
