---
- debug:
    msg: Recreating Radicale container
  when: recreate_radicale_container

- name: Create Radicale docker container
  docker_container:
    recreate: "{{ recreate_radicale_container | default('no') }}"
    name: "{{ radicale_container_name }}"
    image: "{{ radicale_image_name }}"
    state: started
    ports: "{{ radicale_published_ports }}"
    init: yes
    capabilities: "{{ radicale_cap_adds }}"
    cap_drop: "{{ radicale_cap_drops }}"
    pids_limit: "{{ radicale_pids_limit }}"
    memory: "{{ radicale_memory }}"
    healthcheck: "{{ radicale_healthcheck }}"
    volumes: "{{ radicale_volumes }}"
    restart: yes
    restart_policy: unless-stopped
