---
- name: Create Docker container
  docker_container:
    name: "{{ radicale_container_name }}"
    image: "{{ radicale_image_name }}"
    ports: "{{ radicale_published_ports }}"
    capabilities: "{{ radicale_cap_adds }}"
    cap_drop: "{{ radicale_cap_drops }}"
    pids_limit: "{{ radicale_pids_limit }}"
    memory: "{{ radicale_memory }}"
    healthcheck: "{{ radicale_healthcheck }}"
    volumes: "{{ radicale_volumes }}"
    init: yes
    recreate: yes # TODO: recreate only if image has changed or required
    restart: yes
    restart_policy: unless-stopped
    state: started

- name: Symlink inflcoud config.js in Docker container
  shell: |
    docker exec "{{ radicale_container_name }}" ln -f -s /config/infcloud/config.js /usr/lib/python3.7/site-packages/radicale_infcloud/web/config.js
