---
- import_tasks: include-vars.yml

- name: Setup Radicale configuration
  import_tasks: setup-config.yml

- name: Setup Radicale Docker configuration Git
  become: yes
  become_user: root
  import_tasks: setup-git.yml

- import_tasks: create-docker-image.yml

- name: Create Radicale Docker container
  import_tasks: create-docker-container.yml
