---
- import_tasks: include-vars.yml

- name: Setup Radicale configuration
  import_tasks: setup-config.yml

- become: yes
  become_user: root
  block:
    - name: Setup Radicale Docker configuration Git
      include_role:
        name: git-project-setup
      vars:
        git_repository: "{{ radicale_repository }}"
        git_destination: "{{ radicale_docker_destination }}"
        git_directory: "{{ radicale_docker_git_directory }}"
        git_directory_owner: "{{ radicale_docker_git_ownership.owner }}"
        git_directory_group: "{{ radicale_docker_git_ownership.group }}"

- import_tasks: create-docker-image.yml

- name: Create Radicale Docker container
  import_tasks: create-docker-container.yml
