---
- name: Port for Syncthing web UI
  community.general.ufw:
    rule: allow
    port: '8384'

- community.general.ufw:
    rule: allow
    port: '22000'
    proto: tcp

- community.general.ufw:
    rule: allow
    port: '22000'
    proto: udp

- community.general.ufw:
    rule: allow
    port: '21027'
    proto: udp
